//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoIPainter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VoIPainter.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AudioFilter {
            get {
                return ResourceManager.GetString("AudioFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image contrast automatically lowered.
        /// </summary>
        internal static string AutoDuckedContrast {
            get {
                return ResourceManager.GetString("AutoDuckedContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast box applied..
        /// </summary>
        internal static string ContrastBox {
            get {
                return ResourceManager.GetString("ContrastBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string ErrorNoFile {
            get {
                return ResourceManager.GetString("ErrorNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string ImageResizeModeCenter {
            get {
                return ResourceManager.GetString("ImageResizeModeCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        internal static string ImageResizeModeCrop {
            get {
                return ResourceManager.GetString("ImageResizeModeCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        internal static string ImageResizeModeStretch {
            get {
                return ResourceManager.GetString("ImageResizeModeStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1}]: {2}.
        /// </summary>
        internal static string LogFormat {
            get {
                return ResourceManager.GetString("LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LogSeverityError {
            get {
                return ResourceManager.GetString("LogSeverityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string LogSeverityInfo {
            get {
                return ResourceManager.GetString("LogSeverityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string LogSeverityWarning {
            get {
                return ResourceManager.GetString("LogSeverityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string MessageBoxUpdateAvailableCaption {
            get {
                return ResourceManager.GetString("MessageBoxUpdateAvailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available: {0} ({1})
        ///Would you like to download this update?
        ///
        ///Release Notes: {2}.
        /// </summary>
        internal static string MessageBoxUpdateAvailableText {
            get {
                return ResourceManager.GetString("MessageBoxUpdateAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Contrast.
        /// </summary>
        internal static string MessageBoxWarnContrastCaption {
            get {
                return ResourceManager.GetString("MessageBoxWarnContrastCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected image has a high contrast. It may be difficult to read UI elements. Attempt to lower contrast?.
        /// </summary>
        internal static string MessageBoxWarnContrastText {
            get {
                return ResourceManager.GetString("MessageBoxWarnContrastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error.
        /// </summary>
        internal static string PhoneErrorAuthentication {
            get {
                return ResourceManager.GetString("PhoneErrorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error framing CiscoIPPhoneResponse object.
        /// </summary>
        internal static string PhoneErrorFramingResponse {
            get {
                return ResourceManager.GetString("PhoneErrorFramingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal file error.
        /// </summary>
        internal static string PhoneErrorInternalFile {
            get {
                return ResourceManager.GetString("PhoneErrorInternalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing CiscoIPPhoneExecute object.
        /// </summary>
        internal static string PhoneErrorParsingRequest {
            get {
                return ResourceManager.GetString("PhoneErrorParsingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled.
        /// </summary>
        internal static string StatusCanceled {
            get {
                return ResourceManager.GetString("StatusCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing....
        /// </summary>
        internal static string StatusClosing {
            get {
                return ResourceManager.GetString("StatusClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string StatusFinished {
            get {
                return ResourceManager.GetString("StatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting image....
        /// </summary>
        internal static string StatusFormattingImage {
            get {
                return ResourceManager.GetString("StatusFormattingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done formatting image.
        /// </summary>
        internal static string StatusFormattingImageDone {
            get {
                return ResourceManager.GetString("StatusFormattingImageDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting ringtone....
        /// </summary>
        internal static string StatusFormattingTone {
            get {
                return ResourceManager.GetString("StatusFormattingTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done formatting ringtone.
        /// </summary>
        internal static string StatusFormattingToneDone {
            get {
                return ResourceManager.GetString("StatusFormattingToneDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting image server....
        /// </summary>
        internal static string StatusImageServerStarting {
            get {
                return ResourceManager.GetString("StatusImageServerStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image server stopped.
        /// </summary>
        internal static string StatusImageServerStopped {
            get {
                return ResourceManager.GetString("StatusImageServerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping image server....
        /// </summary>
        internal static string StatusImageServerStopping {
            get {
                return ResourceManager.GetString("StatusImageServerStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requested image.
        /// </summary>
        internal static string StatusPhoneRequestImage {
            get {
                return ResourceManager.GetString("StatusPhoneRequestImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requested invalid file &apos;{1}&apos;.
        /// </summary>
        internal static string StatusPhoneRequestInvalid {
            get {
                return ResourceManager.GetString("StatusPhoneRequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} made a request, but VoIPainter was not ready.
        /// </summary>
        internal static string StatusPhoneRequestNotReady {
            get {
                return ResourceManager.GetString("StatusPhoneRequestNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requested ringtone.
        /// </summary>
        internal static string StatusPhoneRequestRingtone {
            get {
                return ResourceManager.GetString("StatusPhoneRequestRingtone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requested thumbnail.
        /// </summary>
        internal static string StatusPhoneRequestThumbnail {
            get {
                return ResourceManager.GetString("StatusPhoneRequestThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending command to phone....
        /// </summary>
        internal static string StatusPhoneSendingCommand {
            get {
                return ResourceManager.GetString("StatusPhoneSendingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string StatusSuccess {
            get {
                return ResourceManager.GetString("StatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        internal static string StatusUpdateCheck {
            get {
                return ResourceManager.GetString("StatusUpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished checking for updates.
        /// </summary>
        internal static string StatusUpdateCheckDone {
            get {
                return ResourceManager.GetString("StatusUpdateCheckDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check for updates: {0}.
        /// </summary>
        internal static string StatusUpdateCheckFail {
            get {
                return ResourceManager.GetString("StatusUpdateCheckFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update available.
        /// </summary>
        internal static string StatusUpdateCheckNegative {
            get {
                return ResourceManager.GetString("StatusUpdateCheckNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        internal static string StatusUpdateCheckPositive {
            get {
                return ResourceManager.GetString("StatusUpdateCheckPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgraded settings to current version.
        /// </summary>
        internal static string StatusUpgradeSettings {
            get {
                return ResourceManager.GetString("StatusUpgradeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        internal static string TitleSelectImage {
            get {
                return ResourceManager.GetString("TitleSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Ringtone.
        /// </summary>
        internal static string TitleSelectRingtone {
            get {
                return ResourceManager.GetString("TitleSelectRingtone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed: {0}.
        /// </summary>
        internal static string TRequestFailed {
            get {
                return ResourceManager.GetString("TRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed: {0}: {1}.
        /// </summary>
        internal static string TRequestFailedMessage {
            get {
                return ResourceManager.GetString("TRequestFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target contrast must be between 0 and 1.
        /// </summary>
        internal static string ValdidationTargetContrast {
            get {
                return ResourceManager.GetString("ValdidationTargetContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fade out time must be between 0 and 20 seconds.
        /// </summary>
        internal static string ValidationFadeOutTime {
            get {
                return ResourceManager.GetString("ValidationFadeOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An image is required.
        /// </summary>
        internal static string ValidationImage {
            get {
                return ResourceManager.GetString("ValidationImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid target IP address is required.
        /// </summary>
        internal static string ValidationIp {
            get {
                return ResourceManager.GetString("ValidationIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone model.
        /// </summary>
        internal static string ValidationModel {
            get {
                return ResourceManager.GetString("ValidationModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password is required.
        /// </summary>
        internal static string ValidationPassword {
            get {
                return ResourceManager.GetString("ValidationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resize mode.
        /// </summary>
        internal static string ValidationResizeMode {
            get {
                return ResourceManager.GetString("ValidationResizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A username is required.
        /// </summary>
        internal static string ValidationUsername {
            get {
                return ResourceManager.GetString("ValidationUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected image has a high contrast. It may be difficult to read UI elements..
        /// </summary>
        internal static string WarnImageContrast {
            get {
                return ResourceManager.GetString("WarnImageContrast", resourceCulture);
            }
        }
    }
}
